# Generated by Django 3.2.9 on 2021-11-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
